version: "3"
services:
  php:
    image: php:7.1-fpm-alpine
    build: './.setup/php/'
    networks:
      - AMP
    volumes:
      - ./public_html/:/var/www/html/
  apache:
    image: httpd:2.4-alpine
    build: './.setup/apache/'
    depends_on:
      - php
    networks:
      - AMP
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./public_html/:/var/www/html/
      - ./.setup/apache/docker.apache.conf:/usr/local/apache2/conf.d/docker.apache.conf
      - ./.setup/apache/logs/:/usr/local/apache2/logs
  mysql:
    image: mysql:5.6
    volumes:
      - ./.setup/mysql/data/:/var/lib/mysql/
    networks:
      - AMP
    environment:
      - MYSQL_ROOT_PASSWORD=docker
    ports:
      - "3306:3306"
  myadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: docker
    depends_on:
      - mysql
    networks:
    - AMP
    ports:
    - "8080:80"
   ftpd_server:
    image: stilliard/pure-ftpd:hardened
    container_name: pure-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes: 
      - "/home/mx/project_sys/public_html:/home/mx/"
      - "/etc/pure-ftpd/passwd:/etc/pure-ftpd/passwd"
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: mx
      FTP_USER_PASS: docker
      FTP_USER_HOME: /home/mx
    restart: always
  # nginx:
  #   image: nginx:stable-alpine
  #   build: './.setup/nginx/'
  #   depends_on:
  #     - php
  #   ports:
  #     - "443:443"
  #     - "80:80"
  #   networks:
  #     - AMP
  #   volumes:
  #     - ./public_html/:/var/www/docker/
  #     - ./.setup/nginx/docker.conf:/etc/nginx/conf.d/default.conf
networks:
  AMP:
